events {}
http {
    # Inclui os tipos de arquivo padrão (para css e js funcionarem)
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    server {
        listen 8080;
        server_name localhost;

        # Configuração da raiz (Note que NÃO tem /dist no final, pois o Docker já resolveu isso)
        root /usr/share/nginx/html;
        index index.html;

        # Regra principal para funcionar o React
        location / {
            try_files $uri $uri/ /index.html;
        }

        # Garante que arquivos JS e CSS sejam lidos corretamente
        location ~* \.(js|css|png|jpg|jpeg|gif|ico)$ {
            expires 1y;
            add_header Cache-Control "public, no-transform";
        }
    }
}
